Repository SSUMC-6th/Spring_Boot_C, pull requests merged in 2024-05, with the labels that each got.

#12 [sof] Chapter03_Web Server & Web Application Server(WAS), Reverse Proxy #12
  docs/chapter3/Ch03Keyword.md
  docs/chapter3/image/ch3_image_01.png
  docs/chapter3/image/ch3_image_02.png
  docs/chapter3/image/ch3_image_03.png
Labels: ✨ Chapter03

#11 [suffle] Chapter03_Web Server & Web Application Server(WAS), Reverse Proxy
  docs/chapter3/Chapter 3. Web Server & Web Application Server(WAS), Reverse Proxy.md
  docs/chapter3/img/Pasted image 20240429131220.png
  docs/chapter3/img/Pasted image 20240429132114.png
  docs/chapter3/img/Pasted image 20240429132137.png
  docs/chapter3/img/Pasted image 20240429132344.png
Labels: ✨ Chapter03

#10 [ming] Chapter03_Web Server & Web Application Server(WAS), Reverse Proxy
  docs/chapter3/Ch03Keyword.md
Labels: ✨ Chapter03

#15 [sof] Chapter 4. DATABASE 설계 & AWS RDS 설정
  docs/chapter4/Ch04Keyword.md
  src/mission/chapter4/ch4_image_01.png
Labels: ✨ Chapter04

#16 [ming] Chapter 4. DATABASE 설계 & AWS RDS 설정
  docs/chapter4/Ch04Keyword.md
  docs/chapter4/img/ER diagram.png
  docs/chapter4/img/N1.png
  docs/chapter4/img/NN.png
  docs/chapter4/img/candidate.png
  docs/chapter4/img/superkey.png
  src/mission/chapter4/ERD.png
Labels: ✨ Chapter04

#14 [suffle] Chapter 4. DATABASE 설계 & AWS RDS 설정
  docs/chapter4/Chapter 4. DATABASE 설계 & AWS RDS 설정.md
Labels: ✨ Chapter04

#18 [Suffle] Chapter 5. 실전 SQL 어떤 Query를 작성해야 할까
  docs/chapter5/Chapter 5. 실전 SQL 어떤 Query를 작성해야 할까.md
Labels: ✨ Chapter05

#19 [ming] Chpater05_실전 SQL - 어떤 Query를 작성해야 할까?
  src/mission/chapter5/chapter5.sql
Labels: ✨ Chapter05

#20 [sof] Chpater05_실전 SQL - 어떤 Query를 작성해야 할까?
  src/mission/chapter5/ch5_mission.sql
Labels: ✨ Chapter05

#22 [ming] Chapter06_API URL의 설계 & 프로젝트 세팅
  src/mission/chapter6/Ch06Mission_API.png
  src/practice/chapter6/spring/.gitignore
  src/practice/chapter6/spring/build.gradle
  src/practice/chapter6/spring/gradle/wrapper/gradle-wrapper.jar
  src/practice/chapter6/spring/gradle/wrapper/gradle-wrapper.properties
  src/practice/chapter6/spring/gradlew
  src/practice/chapter6/spring/gradlew.bat
  src/practice/chapter6/spring/settings.gradle
  src/practice/chapter6/spring/src/main/java/umc/spring/Application.java
  src/practice/chapter6/spring/src/main/resources/application.properties
  src/practice/chapter6/spring/src/test/java/umc/spring/ApplicationTests.java
Labels: ✨ Chapter06

#23 [suffle] chapter06.API URL의 설계 & 프로젝트 세팅
  src/mission/ch06.api/chapter06.API URL의 설계 & 프로젝트 세팅.md
Labels: ✨ Chapter06

#24 [sof] chapter06_API URL의 설계 & 프로젝트 세팅
  docs/chapter6/Ch06Keyword.md
  docs/chapter6/image/ch6_image_02.png
  docs/chapter6/image/ch6_image_03.png
  docs/chapter6/image/ch6_image_04.png
  docs/chapter6/image/ch6_image_05.png
  docs/chapter6/image/ch6_image_06.png
  docs/chapter6/image/ch6_image_07.png
  docs/chapter6/image/ch6_image_08.png
  docs/chapter6/image/ch6_image_09.png
  src/mission/chapter6/ch6_image_01.png
Labels: ✨ Chapter06

#28 [sof] Chapter07_JPA를 통한 엔티티 설계, 매핑 & 프로젝트 파일 구조 이해
  .idea/.gitignore
  .idea/Spring_Boot_C.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  docs/chapter7/Ch07Keyword.md
  src/mission/chapter7/ch7_image_01.png
  src/mission/chapter7/ch7_image_02.png
Labels: ✨ Chapter07

#26 [ming] Chapter07_JPA를 통한 엔티티 설계, 매핑 & 프로젝트 파일 구조 이해
  docs/chapter7/Ch07Keyword.txt
  src/mission/chapter4/ERD.png
  src/practice/chapter6/spring/.gitignore
  src/practice/chapter6/spring/build.gradle
  src/practice/chapter6/spring/gradle/wrapper/gradle-wrapper.jar
  src/practice/chapter6/spring/gradle/wrapper/gradle-wrapper.properties
  src/practice/chapter6/spring/gradlew
  src/practice/chapter6/spring/gradlew.bat
  src/practice/chapter6/spring/settings.gradle
  src/practice/chapter6/spring/src/main/java/umc/spring/Application.java
  src/practice/chapter6/spring/src/main/resources/application.properties
  src/practice/chapter6/spring/src/test/java/umc/spring/ApplicationTests.java
Labels: ✨ Chapter07
